function login(b){function c(a,b){window.__sparkUser=null;var c=new hi5.WebSocket(a);c.onclose=function(a){f||(alert(__svi18n.errorCode.connection),showLogDlg());f=!1;hi5.tool.enableInput()};c.onopen=function(a){f=!0};c.onmessage=function(a){a=JSON.parse(a.data);a.error||c.send("A1"+navigator.userAgent);b(a);c.close()};return!1}function d(a){hi5.tool.enableInput();if(a.error)alert(__svi18n.errorCode["S"+a.name]);else{document.getElementById("frmLogin").style.display="none";document.getElementById("frmConn").style.display=
"block";for(var c=document.getElementById("programs");c.hasChildNodes();)c.removeChild(c.firstChild);var b=a.servers;if(!a.accessNotInList){var d=document.getElementById("anyconn");d&&(d.style.display="none")}window.__sparkUser={session:a.session,account:document.getElementById("user").value,gateway:document.getElementById("gateway").value,servers:b};a=b.length;if(!(1>a))for(d=0;d<a;d++){var f=b[d].server,e=b[d].id,f=b[d].displayName||e||f,l=b[d].icon;l||(l="rdp32.png");var h=document.createElement("div");
h.className="icon";var g=document.createElement("img");g.src=l;g.id=e;g.alt=e;g.title=f;g.style.cursor="pointer";g.onclick=connectSelected;h.appendChild(g);h.appendChild(document.createElement("br"));h.appendChild(document.createTextNode(f));c.appendChild(h)}}}hi5.tool.disableInput();var f=!1,e=hi5.browser.cookie2Obj();e.svSession&&e.svEmail&&(b+="&svSession="+e.svSession+"&svEmail="+encodeURIComponent(e.svEmail));setTimeout(function(){c(b,d)},5);return!1}
function connectSelected(b){var c=b.target;c.onclick=null;setTimeout(function(){c.onclick=connectSelected},300);connect(c.id)}
function connect(b){var c=window.__sparkUser,d=c.servers,f=d.length;c.server=null;window.sparkGateway=c.gateway;for(var e=0;e<f;e++){var a=d[e];if(b==a.id){a=connvertServer(a);a.gateway=c.gateway;a.session=c.session;a.account=c.account;c.server=a;f=a.server_bpp;b=window.innerWidth;d=window.innerHeight;a.width=b;a.height=d;f||(f=16);a.width=b;a.height=d;a.color=f;break}}if(c.server){(a=document.getElementById("touchpad"))&&a.checked&&(c.server.touchpad=!0);if(a=document.getElementById("keyboard"))a=
parseInt(a.options[a.selectedIndex].value),0<a&&(c.server.keyboard=a);a=(a=document.getElementById("sameWindow"))&&a.checked;if("app"==c.server.startProgram&&hi5.browser.isMultitask&&!a)openRail();else if(a){var k=new Rdp2(c.server);$id("login").style.display="none";k.addSurface(new svGlobal.LocalInterface);k.run();k.onclose=function(){k.hide();$id("login").style.display="block"}}else window.open("rdpdirect.html")}else alert("Not a valid server")}
function startExitingApp(b){function c(a){d.addSurface(a);d.startExitingApp(b)}var d=svManager.getInstance();window.svOnSurfaceReady=c;window.open("rail.html").svOnSurfaceReady=c;var f=document.getElementById(b),e=f.parentNode;e.removeChild(f);e=e.parentNode;0==e.getElementsByTagName("input").length&&(e.dismiss(),d.checkRemaining(2E3))}
function openRail(){function b(b){d.addSurface(b);d.running()?d.startApp(c.exe,c.args,""):d.run()}var c=window.__sparkUser.server,d=svManager.getInstance();null==d&&(d=new svGlobal.Rdp2(c),d.sessionTimeout=9E5);window.svOnSurfaceReady=b;window.open("rail.html").svOnSurfaceReady=b}function openDesktop(b){window.open("rdp.html?gateway="+document.getElementById("gateway").value)}
function showLogDlg(){window.__sparkUser=null;var b=document.getElementById("frmLogin");b.elements.pwd.value="";b.style.display="block";document.getElementById("frmConn").style.display="none";(b=svManager.getInstance())&&b.running()&&b.close()}window.addEventListener("load",function(b){document.getElementById("user").focus();b=hi5.browser.cookie2Obj();if(b.svSession&&b.svEmail){var c=$id("frmLogin").elements;c.user.value=b.svEmail;c.pwd.value="fake";setTimeout(start,1E3)}},!1);
